### ISSUE TITLE
Simplifications for v0.14

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#1448]
Given the evolving use-cases for Iter8 (including traffic engineering use-cases), it is worth simplifying a few aspects of Iter8 in v0.14. A partial list of these simplifications are as follows.

- [x] Use `go install` for Iter8. `go install` is a powerful command that supports multiple architectures, minor version prefixes, SHA/commit-id based install, as well as installations from PR branches, and `latest` already. This means, we don't need `binaries`, `homebrew`, and `GitHub action` for Iter8 install.
- [x] Merge `hub` repo into `iter8` repo. This way, we will still have a `helm` repo for installing Iter8 helm charts (and not a Git repo). However, we will not have two repos, only one. So, `iter8` will become a mono repo, containing both `Go` code, and `Helm` charts.
- [ ] Remove the `iter8 k` subcommand and replace them with the appropriate `iter8` subcommands. `iter8 k` persistent flags will be absorbed as part of `iter8` persistent flags.
- [x] Ensure that ABn controller re-uses the same config struct/file as the traffic controller. This is a breaking change since for ABn since the config information it uses today is somewhat different. Installation of ABn will need to change accordingly. Also, it will use the `routemap` weights directly from the traffic controller as part of its lookup call, to support weighted routing.

**Comment by kalantar** [comment]
This is no longer a v0.14 item. Closing the "epic"; the remaining isssue still present
