### ISSUE TITLE
For SDK based A/B/n tests, enable visualization of result in Grafana

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1501]
Consider exposing raw metrics (instead of just summary metrics) and doing summary metric/best computations in Grafana if possible.

Issues related to Grafana

- [x]  https://github.com/iter8-tools/iter8/issues/1507
- [x] https://github.com/iter8-tools/iter8/issues/1515
- [x] https://github.com/iter8-tools/iter8/issues/1521
- [ ] ~~https://github.com/iter8-tools/iter8/issues/1522 (nice to have)~~

Supporting storage client changes

- [x] https://github.com/iter8-tools/iter8/issues/1506 (completed PR https://github.com/iter8-tools/iter8/pull/1511)

Supporting Metrics Service

- [x] https://github.com/iter8-tools/iter8/issues/1512
- [x] https://github.com/iter8-tools/iter8/issues/1514 (dependent on https://github.com/iter8-tools/iter8/issues/1506)
- [x] https://github.com/iter8-tools/iter8/issues/1516

Issues related to Iter8

- [x] https://github.com/iter8-tools/iter8/issues/1477 (completed PR https://github.com/iter8-tools/iter8/pull/1493)
- [x] https://github.com/iter8-tools/iter8/issues/1499 (completed PR https://github.com/iter8-tools/iter8/pull/1493)
- [x] https://github.com/iter8-tools/iter8/issues/1518 (completed PR https://github.com/iter8-tools/iter8/pull/1493)
- [x] https://github.com/iter8-tools/iter8/issues/1517
- [x] https://github.com/iter8-tools/iter8/issues/1513 (in review PR https://github.com/iter8-tools/docs/pull/95)

**Comment by sriumcp** [comment]
Assume there is a way to get JSON data for an app, specifically, summary metrics for an app. Display this in a Grafana dashboard. 

For starts, it can reflect the information in Iter8 report for ABn testing experiments. Going a step further, may be, for each metric, we can also get the raw values, and plot histograms.

For each metric, histograms, and summaries can be computed at both the user level and transaction.
***
In this exercise, for Grafana data source: create a `gist`, and use simple JSON plugin/Infinity plugin in Grafana as a way to get to this data.
***
Go beyond this exercise, once we nail the Grafana viz panels, we can start creating service APIs in Iter8 that supply this JSON data.
