### ISSUE TITLE
Refine controller documentation

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1503]
Parent issue for a number of controller related documentation issues:

- [ ] KServe modelmesh - mirroring (issue https://github.com/iter8-tools/iter8/issues/1508)
- [x] regular KServe - blue-green, canary (issues https://github.com/iter8-tools/iter8/issues/1509 and https://github.com/iter8-tools/iter8/issues/1510)
- [x] gettting started (issues https://github.com/iter8-tools/iter8/issues/1491 and https://github.com/iter8-tools/iter8/issues/1443)
- [x] adding CRD (https://github.com/iter8-tools/iter8/issues/1502)

**Comment by kalantar** [comment]
closing; remaining issue still present.
