### ISSUE TITLE
ODH-Iter8 MVP

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1530]
This epic captures all issues related to initial mvp for ODH

- [x] [Create ODH working group](https://github.com/iter8-tools/iter8/issues/1529)
- [x] [Document blue-green scenario for kserve serving](https://github.com/iter8-tools/iter8/issues/1509) -- included in PR https://github.com/iter8-tools/docs/pull/98
- [x] [Document canary scenario for kserve serving](https://github.com/iter8-tools/iter8/issues/1510) -- included in PR https://github.com/iter8-tools/docs/pull/98
- [ ] [Document mirroring scenario for kserve model-mesh serving](https://github.com/iter8-tools/iter8/issues/1508)
- [x] [Install Iter8 as part of ODH installation](https://github.com/iter8-tools/iter8/issues/1531)
- [x] [Document service mesh configuation for Iter8](https://github.com/iter8-tools/iter8/issues/1561)

**Comment by kalantar** [comment]
considering complete after release in ODH
