### ISSUE TITLE
CNCF submission

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1600]
Epic to capture items related to submission of Iter8 to CNCF sandbox project.

**Documentation updates**
- [x] https://github.com/iter8-tools/iter8/issues/1618 (https://github.com/iter8-tools/docs/pull/108)
- [x] https://github.com/iter8-tools/iter8/issues/1619 (https://github.com/iter8-tools/docs/pull/108)
- [x] https://github.com/iter8-tools/iter8/issues/1500
- [x] release chart documentation

**Code updates**
- [x] https://github.com/iter8-tools/iter8/issues/1492
- [x] https://github.com/iter8-tools/iter8/issues/1606
- [x] https://github.com/iter8-tools/iter8/issues/1611
- [x] https://github.com/iter8-tools/iter8/pull/1615
- [x] release chart
- [ ] explore kubernetes gateway API
- [ ] [scaling/persistence of metrics data collection](https://github.com/iter8-tools/iter8/issues/1648)

**Other changes to consider**
- [x] https://github.com/iter8-tools/iter8/issues/1598
- [x] https://github.com/iter8-tools/iter8/issues/1617
- [x] https://github.com/iter8-tools/iter8/issues/1620
