### ISSUE TITLE
[Release checklist] Remaining items for Iter8 v0.3.0 release

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8#537]
### weight fix 
- [x] Merge etc3 weight fix changes into etc3 repo
- [x] Update etc3 image in iter8-install repo
- [x] Create tagged release v0.3.0-pre.1 in iter8-install repo
- [x] Remove install folder from iter8 repo
- [ ] Merge new samples and documentation based on v0.3.0-pre.1 in iter8 repo
  - [ ] Update documentation (both install instructions and others like samples / references)
  - [ ] Update platform setup
  - [ ] Verify automated and manual tests succeed
---
### jq changes; multi-domain multi-db install changes
- [x] Finish test cases for iter8-analytics and merge
- [x] Update iter8-analytics image in iter8-install repo
- [x] Finish and merge jqExpression CRD changes in etc3 repo
- [x] Update etc3 image in iter8-install repo
- [x] Create multi-domain and multi-db install in iter8-install repo
  - [x] Focus on knative
  - [x] Ensure that `iter8-system` namespace is kustomizable
- [ ] Create tagged release v0.3.0-pre.2 in iter8-install repo
- [ ] Merge new samples and documentation based on v0.3.0-pre.2 in iter8 repo
  - [ ] Update documentation (both install instructions and others like samples / references)
  - [ ] Update platform setup
  - [ ] Verify automated and manual tests succeed
---
### sample to demonstrate multi db
- [ ] Create a sample that showcases multiple database usage for Knative
  - [ ] Focus on Prometheus + NewRelic; canary
  - **Note:** creating a sample always means creating corresponding tests and documentation
---
### cleanup
- [ ] Clean up what is iter8
- [ ] Clean up title of documentation sections
- [ ] Clean up titles of tutorials and their organization
---
### what always happens before a release (announcement)
- [ ] Create a release branch for iter8 v0.3.0 (we always create immutable release branches for iter8 releases; branch is for Netlify purposes only)
- [ ] Create (only for this type; usually this an update) `what is new?` section of the documentation
